/**
 * @file I021_260.h
 * @brief Definition of I021/260, and related functions and values
 */

#ifndef I021_260_H
#define I021_260_H

#include <stdint.h>
#include "Common/visibility.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Macros
 ******************************************************************************/

#define I021_260_N_OCTETS                         7 /// Number of octets 

/*******************************************************************************
 * Structures and Types
 ******************************************************************************/

/**
 * @typedef I021_260
 * @brief Category 021 / Item 260 - ACAS Resolution Advisory Report
 * 
 * Currently active Resolution Advisory (RA), if any, generated by
 * the ACAS associated with the transponder transmitting the RA
 * message and threat identity data.
 */
typedef struct I021_260 {
    union {
        /// @brief Raw octets as received (recommended for portable access)
        uint8_t raw[I021_260_N_OCTETS];

        /**
         * @note Bit-field layout is compiler and endianness dependent.
         * Use raw field and provided macros for portable access.
         */

        /// @brief Bit-field access (might be non-portable, use with caution)
        struct {
            /**
             * @brief Message Type (= 28 for 1090 ES, Version 2 or higher) (bits-56/52)
             * 
             * @note The value is implementation (i.e. link technology) dependent
             * @note “Version 2 or higher” denotes the MOPS version as defined
             *       in I021/210, bits 6/4
             */
            uint8_t  TYP            :5;
            /**
             * @brief Message Sub-type (= 2 for 1090 ES, Version 2 or higher) (bits-51/49)
             * 
             * @note The value is implementation (i.e. link technology) dependent
             * @note “Version 2 or higher” denotes the MOPS version as defined
             *       in I021/210, bits 6/4
             */
            uint8_t  STYP           :3;
            /// @brief Active Resolution Advisories (bits-48/41)
            uint8_t  ARA;
            /// @brief ARA continuation (bits-40/35)
            uint16_t  ARA_ctd        :6;
            /// @brief RAC (RA Complement) Record (bits-34/31)
            uint16_t  RAC            :4;
            /// @brief RA Terminated (bit-30)
            uint16_t  RAT            :1;
            /// @brief Multiple Threat Encounter (bit-29)
            uint16_t  MTE            :1;
            /// @brief Threat Type Indicator (bits-28/27)
            uint16_t  TTI            :2;
            /// @brief Threat Identity Data (bits-26/25)
            uint16_t  TID            :2;
            /// @brief Threat Identity Data continuation 1 (bits-24/9)
            uint16_t TID_ctd_1;
            /// @brief Threat Identity Data continuation 2 (bits-8/1)
            uint8_t TID_cte_2;
        };
    };
} I021_260;

/*******************************************************************************
 * Getters
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_TYP(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_STYP(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint16_t get_I021_260_ARA(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_RAC(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_RAT(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_MTE(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint8_t get_I021_260_TTI(const I021_260 * item);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API uint32_t get_I021_260_TID(const I021_260 * item);

/*******************************************************************************
 * Setters
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_TYP(I021_260 * item, uint8_t typ);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_STYP(I021_260 * item, uint8_t styp);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_ARA(I021_260 * item, uint16_t ara);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_RAC(I021_260 * item, uint8_t rac);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_RAT(I021_260 * item, uint8_t rat);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_MTE(I021_260 * item, uint8_t mte);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_TTI(I021_260 * item, uint8_t tti);

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void set_I021_260_TID(I021_260 * item, uint32_t tid);

/*******************************************************************************
 * Encoding and Decoding functions
 ******************************************************************************/

/** @brief Encode item I021/008 (ACAS Resolution Advisory Report) into a raw ASTERIX message.
 *
 * @param item_in Pointer to the input I021/008 structure.
 * @param msg_out Pointer to the output ASTERIX message buffer.
 * @param out_index Current index in the output message buffer.
 * 
 * @return Updated index in the output message buffer after encoding.
 */
ASTERIX_API uint16_t encode_I021_260(void * item_in,
                                     unsigned char * msg_out,
                                     uint16_t out_index);

/** @brief Decode item I021/008 (ACAS Resolution Advisory Report) from a raw ASTERIX message.
 *
 * @param item_out Pointer to the output I021/008 structure to populate.
 * @param msg_in Pointer to the input ASTERIX message buffer.
 * @param in_index Current index in the input message buffer.
 * 
 * @return Updated index in the input message buffer after decoding.
 */
ASTERIX_API uint16_t decode_I021_260(void * item_out,
                                     const unsigned char * msg_in,
                                     uint16_t in_index);

/*******************************************************************************
 * Other Functions
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to I021_260 structure
 */
ASTERIX_API void print_I021_260(const I021_260 * item);

#ifdef __cplusplus
}
#endif

#endif /* I021_260_H */