/**
 * @file cat021_item260.h
 * @brief Definition of CAT 021 Item 260, and related functions and values
 */

#ifndef CAT021_ITEM260_H
#define CAT021_ITEM260_H

#include <stdint.h>
#include "Common/visibility.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Macros
 ******************************************************************************/

#define CAT021_ITEM260_N_OCTETS                         7 /// Number of octets 

/*******************************************************************************
 * Structures and Types
 ******************************************************************************/

/**
 * @typedef cat021_item260
 * @brief Category 021 Item 260 - ACAS Resolution Advisory Report
 * 
 * Currently active Resolution Advisory (RA), if any, generated by
 * the ACAS associated with the transponder transmitting the RA
 * message and threat identity data.
 */
typedef struct cat021_item260 {
    union {
        /// @brief Raw octets as received (recommended for portable access)
        uint8_t raw[CAT021_ITEM260_N_OCTETS];

        /**
         * @note Bit-field layout is compiler and endianness dependent.
         * Use raw field and provided macros for portable access.
         */

        /// @brief Bit-field access (might be non-portable, use with caution)
        struct {
            /**
             * @brief Message Type (= 28 for 1090 ES, Version 2 or higher) (bits-56/52)
             * 
             * @note The value is implementation (i.e. link technology) dependent
             * @note “Version 2 or higher” denotes the MOPS version as defined
             *       in I021/210, bits 6/4
             */
            uint8_t  TYP            :5;
            /**
             * @brief Message Sub-type (= 2 for 1090 ES, Version 2 or higher) (bits-51/49)
             * 
             * @note The value is implementation (i.e. link technology) dependent
             * @note “Version 2 or higher” denotes the MOPS version as defined
             *       in I021/210, bits 6/4
             */
            uint8_t  STYP           :3;
            /// @brief Active Resolution Advisories (bits-48/41)
            uint8_t  ARA;
            /// @brief ARA continuation (bits-40/35)
            uint8_t  ARA_ctd        :6;
            /// @brief RAC (RA Complement) Record (bits-34/31)
            uint8_t  RAC            :4;
            /// @brief RA Terminated (bit-30)
            uint8_t  RAT            :1;
            /// @brief Multiple Threat Encounter (bit-29)
            uint8_t  MTE            :1;
            /// @brief Threat Type Indicator (bits-28/27)
            uint8_t  TTI            :2;
            /// @brief Threat Identity Data (bits-26/25)
            uint8_t  TID            :2;
            /// @brief Threat Identity Data continuation 1 (bits-24/9)
            uint16_t TID_ctd_1;
            /// @brief Threat Identity Data continuation 2 (bits-8/1)
            uint8_t TID_cte_2;
        };
    };
} cat021_item260;

/*******************************************************************************
 * Getters
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_TYP(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_STYP(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint16_t get_cat021_item260_ARA(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_RAC(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_RAT(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_MTE(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint8_t get_cat021_item260_TTI(const cat021_item260 * item);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API uint32_t get_cat021_item260_TID(const cat021_item260 * item);

/*******************************************************************************
 * Setters
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_TYP(cat021_item260 * item,
                                        const uint8_t typ);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_STYP(cat021_item260 * item,
                                        const uint8_t styp);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_ARA(cat021_item260 * item,
                                        const uint16_t ara);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_RAC(cat021_item260 * item,
                                        const uint8_t rac);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_RAT(cat021_item260 * item,
                                        const uint8_t rat);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_MTE(cat021_item260 * item,
                                        const uint8_t mte);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_TTI(cat021_item260 * item,
                                        const uint8_t tti);

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void set_cat021_item260_TID(cat021_item260 * item,
                                        const uint32_t tid);

/*******************************************************************************
 * Other Functions
 ******************************************************************************/

/**
 * @brief
 * 
 * @param item pointer to cat021_item260 structure
 */
ASTERIX_API void print_cat021_item260(const cat021_item260 * item);

#ifdef __cplusplus
}
#endif

#endif /* CAT021_ITEM260_H */